// PCDeal V7.2 — Universal hardware alias layer
(()=>{"use strict";
const W=window;
function compact(v){return String(v||"").toLowerCase().replace(/[®™]/g,"").replace(/[–—]/g,"-").replace(/[\s_\-./\\()[\]{}]+/g,"").replace(/[^a-z0-9+]/g,"")}
function spaced(v){return String(v||"").toLowerCase().replace(/[®™]/g,"").replace(/[–—_]/g," ").replace(/([a-z])(\d)/g,"$1 $2").replace(/(\d)([a-z])/g,"$1 $2").replace(/[^a-z0-9+]+/g," ").replace(/\s+/g," ").trim()}
function key(v){return compact(v).replace(/^nvidiageforce|^geforce|^nvidia|^amdradeon|^radeon|^amd|^intelcore|^intel/,"").replace(/processor|graphics|card|gpu|cpu/g,"")}
function cpu(v){let raw=String(v||""),c=key(raw),m;c=c.replace(/^ryzen/,"");m=c.match(/^r?([3579])(\d{4})(x3d|xt|x|g|ge|gt|f)?$/i);if(m)return`Ryzen ${m[1]} ${m[2]}${(m[3]||"").toUpperCase()}`;m=c.match(/^(?:core)?ultra([579])(\d{3})(kf|k|f)?$/i);if(m)return`Core Ultra ${m[1]} ${m[2]}${(m[3]||"").toUpperCase()}`;m=c.match(/^i([3579])(\d{4,5})(ks|kf|k|f|t)?$/i);if(m)return`i${m[1]}-${m[2]}${(m[3]||"").toUpperCase()}`;m=c.match(/^fx(\d{4})$/i);if(m)return`FX-${m[1]}`;let sp=spaced(raw);m=sp.match(/\b(?:ryzen\s*)?r?\s*([3579])\s*(\d{4})\s*(?:x\s*3\s*d|x3d|xt|x|g|ge|gt|f)?\b/i);if(m){let tail=compact(m[0]).match(/(x3d|xt|x|g|ge|gt|f)$/i);return`Ryzen ${m[1]} ${m[2]}${tail?tail[1].toUpperCase():""}`};m=sp.match(/\b(?:core\s*)?i\s*([3579])\s*(\d{4,5})\s*(ks|kf|k|f|t)?\b/i);if(m)return`i${m[1]}-${m[2]}${(m[3]||"").toUpperCase()}`;return raw.trim()}
function gpu(v){let raw=String(v||""),c=key(raw),m;if(/rx|radeon|xtx|\bgre\b/i.test(raw)){m=c.match(/^(?:rx)?(\d{3,4})(xtx|xt|gre)?(?:(\d{1,2})gb)?$/i);if(m)return`RX ${m[1]}${m[2]?" "+m[2].toUpperCase():""}${m[3]?" "+m[3]+"GB":""}`}
if(/arc/i.test(raw)||/^[ab]\s*\d{3}/i.test(raw.trim())){m=c.match(/^(?:arc)?([ab])(\d{3})(?:(\d{1,2})gb)?$/i);if(m)return`Arc ${m[1].toUpperCase()}${m[2]}${m[3]?" "+m[3]+"GB":""}`}
m=c.match(/^(rtx|gtx|gt)?(\d{3,4})(tisuper|tis|ts|ti|super|s)?(?:(\d{1,2})gb)?$/i);if(m){let pref=(m[1]||(+m[2]>=2000?"rtx":+m[2]>=400?"gtx":"gt")).toUpperCase(),s=(m[3]||"").toLowerCase();if(s==="tis"||s==="ts")s="tisuper";let pretty=s==="ti"?" Ti":s==="super"||s==="s"?" Super":s==="tisuper"?" Ti Super":"";return`${pref} ${m[2]}${pretty}${m[4]?" "+m[4]+"GB":""}`}
m=c.match(/^(?:rx)?(\d{3,4})(xtx|xt|gre)?(?:(\d{1,2})gb)?$/i);if(m&&(m[2]||/^(460|470|480|550|560|570|580|590|6400|6500|6600|6650|6700|6750|6800|6900|6950|7600|7700|7800|7900|9060|9070)$/.test(m[1])))return`RX ${m[1]}${m[2]?" "+m[2].toUpperCase():""}${m[3]?" "+m[3]+"GB":""}`;m=c.match(/^(?:arc)?([ab])(\d{3})(?:(\d{1,2})gb)?$/i);if(m)return`Arc ${m[1].toUpperCase()}${m[2]}${m[3]?" "+m[3]+"GB":""}`;return raw.trim()}
const chips=["X870E","X870","B850","B840","X670E","X670","B650E","B650","A620","X570","B550","A520","X470","B450","X370","B350","A320","Z890","B860","H810","Z790","H770","B760","Z690","H670","B660","H610","Z590","H570","B560","H510","Z490","H470","B460","H410","Z390","Z370","H370","B365","B360","H310","Z270","H270","B250","Z170","H170","B150","H110","Z97","H97","Z87","H87","B85","H81","Z77","Z75","H77","B75","H61"];
function mobo(v){let s=spaced(v),c=key(v).toUpperCase(),ch=chips.find(x=>c.includes(x));if(!ch)return String(v||"").trim();let brand=/\bmsi\b/i.test(s)?"MSI":/\basus\b|\brog\b/i.test(s)?"ASUS":/\bgigabyte\b|\baorus\b/i.test(s)?"Gigabyte":/\basrock\b/i.test(s)?"ASRock":"",fam=/tomahawk/i.test(s)?"Tomahawk":/mortar/i.test(s)?"Mortar":/aorus\s*elite/i.test(s)?"Aorus Elite":/tuf\s*gaming/i.test(s)?"TUF Gaming":/rog\s*strix/i.test(s)?"ROG Strix":/steel\s*legend/i.test(s)?"Steel Legend":/\beagle\b/i.test(s)?"Eagle":"";return[brand,ch,fam].filter(Boolean).join(" ")+(/wifi|wi fi/i.test(s)?" WiFi":"")}
function psu(v){let raw=String(v||""),s=spaced(raw),c=key(raw),w=+((raw.match(/\b(\d{3,4})\s*w?\b/i)||[])[1]||0),brand=/\bcorsair\b/i.test(s)?"Corsair":/\bseasonic\b/i.test(s)?"Seasonic":/\bevga\b/i.test(s)?"EVGA":/\bmsi\b/i.test(s)?"MSI":/\bthermaltake\b/i.test(s)?"Thermaltake":/\bcooler\s*master\b|\bcm\b/i.test(s)?"Cooler Master":"",f=(raw.match(/\b(rm\d{3,4}[xe]?|hx\d{3,4}|ax\d{3,4}|sf\d{3,4}|focus\s*(?:gx|px)?\s*\d{3,4}|prime\s*\w*\s*\d{3,4}|supernova\s*\w*\s*\d{3,4}|mwe\s*\w*\s*\d{3,4}|toughpower\s*\w*\s*\d{3,4})\b/i)||[])[1]||"";if(!f){let m=c.match(/^(?:corsair)?(rm\d{3,4}[xe]?|hx\d{3,4}|ax\d{3,4}|sf\d{3,4})$/i);if(m)f=m[1]}return[brand,f,w?`${w}W`:""].filter(Boolean).join(" ")||raw.trim()}
function ram(v){let r=String(v||""),kit=r.match(/\b(\d)\s*[x×]\s*(\d+)\s*g(?:b)?\b/i),tot=kit?+kit[1]*+kit[2]:+((r.match(/\b(4|8|12|16|24|32|48|64|96|128|192|256)\s*g(?:b)?\b/i)||[])[1]||0),gen=(r.match(/\bddr\s*([345])\b/i)||[])[1]||(r.match(/\bd([345])\b/i)||[])[1]||"",spd=+((r.match(/\b([1-9]\d{3})\s*(?:mhz|mt\/s|mts)?\b/i)||[])[1]||0),cl=+((r.match(/\bcl\s*(\d{2,3})\b/i)||[])[1]||0);return[kit?`${kit[1]}x${kit[2]}GB`:tot?`${tot}GB`:"",gen?`DDR${gen}`:"",spd?`${spd}MHz`:"",cl?`CL${cl}`:""].filter(Boolean).join(" ")||r.trim()}
function storage(v){let r=String(v||""),m=r.match(/\b(\d+(?:\.\d+)?)\s*(tb|gb)\b/i),cap=m?`${m[1]}${m[2].toUpperCase()}`:"",c=key(r),type=/nvme|m2nvme/.test(c)?"NVME M.2":/hdd|harddrive/.test(c)?"HDD":/ssd|satassd|m2sata/.test(c)?"SSD":"";return[cap,type].filter(Boolean).join(" ")||r.trim()}
function cooler(v){let r=String(v||""),c=key(r),sz=(r.match(/\b(120|240|280|360|420)\s*mm?\b/i)||[])[1]||"";if(/aio|liquidcool|watercool|kraken|liquidfreezer|galahad|h100|h115|h150|h170/.test(c))return`${sz?sz+"mm ":""}AIO`.trim();if(/nhd15/.test(c))return"Noctua NH-D15";if(/ak620/.test(c))return"DeepCool AK620";if(/peerlessassassin/.test(c))return"Thermalright Peerless Assassin";if(/phantomspirit/.test(c))return"Thermalright Phantom Spirit";if(/hyper212/.test(c))return"Cooler Master Hyper 212";return r.trim()}
function any(k,v){k=String(k||"").toLowerCase();return k==="cpu"?cpu(v):k==="gpu"?gpu(v):k==="motherboard"||k==="mobo"?mobo(v):k==="psu"?psu(v):k==="ram"||k==="memory"?ram(v):k==="storage"||k==="drive"?storage(v):k==="cooler"?cooler(v):String(v||"").trim()}
W.PCDealAliases={compact,spaced,key,normalizeCPUAlias:cpu,normalizeGPUAlias:gpu,normalizeMotherboardAlias:mobo,normalizePSUAlias:psu,normalizeRamAlias:ram,normalizeStorageAlias:storage,normalizeCoolerAlias:cooler,normalizeAnyHardware:any};
const oldCPU=W.findCPU,oldGPU=W.findGPU,oldDCPU=W.detectCPUFromText,oldDGPU=W.detectGPUFromText;
if(typeof oldCPU==="function")W.findCPU=q=>oldCPU(cpu(q))||oldCPU(q);
if(typeof oldGPU==="function")W.findGPU=q=>oldGPU(gpu(q))||oldGPU(q);
W.detectCPUFromText=text=>{let x=typeof oldDCPU==="function"?oldDCPU(text):null;if(x)return x;let raw=String(text||"");for(let n=1;n<=3;n++){let t=raw.split(/\s+/);for(let i=0;i<=t.length-n;i++){let a=cpu(t.slice(i,i+n).join(" "));if(a!==t.slice(i,i+n).join(" ")){let hit=W.findCPU?.(a);if(hit)return hit}}}return null};
W.detectGPUFromText=text=>{let x=typeof oldDGPU==="function"?oldDGPU(text):null;if(x)return x;for(const tok of String(text||"").split(/[\s,;|/]+/)){let a=gpu(tok);if(a!==tok){let hit=W.findGPU?.(a);if(hit)return hit}}return null};
if(typeof W.detectCPUFromListing==="function")W.detectCPUFromListing=text=>W.detectCPUFromText(text)?.name||"";
if(typeof W.detectGPUFromListing==="function")W.detectGPUFromListing=text=>W.detectGPUFromText(text)?.name||"";
})();