
// ============================================================
// PCDEAL V4.0 SHARED FEATURE LAYER
// Multi-page intelligence tools (20-feature expansion)
// ============================================================
(function(){
"use strict";
const STORAGE_KEY="pcdeal.v4.build";
const $=id=>document.getElementById(id);
const val=id=>$(id)?.value?.trim?.()||$(id)?.value||"";
const num=v=>Number(v)||0;
const money=v=>Number.isFinite(Number(v))?new Intl.NumberFormat("en-CA",{style:"currency",currency:getState().currency||"CAD",maximumFractionDigits:0}).format(Number(v)):"—";
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function getState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}")||{}}catch{return {}}}
function saveState(s){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(s))}catch{} return s}
function currentListing(){return val("listingText")||getState().listing||""}
function safeFindCPU(name){try{return typeof findCPU==="function"?findCPU(name):null}catch{return null}}
function safeFindGPU(name){try{return typeof findGPU==="function"?findGPU(name):null}catch{return null}}
function perfOf(part){return num(part?.performance)}
function valueOf(part){return num(part?.value)}
function extractPSUW(text){const m=String(text||"").match(/\b(\d{3,4})\s*w\b/i);return m?num(m[1]):0}
function detectDrives(text){
 const raw=String(text||""); const found=[]; const rx=/\b(\d+(?:\.\d+)?)\s*(tb|gb)\b[^\n,;+|]{0,45}?\b(m\.2\s*nvme(?:\s*ssd)?|nvme\s*ssd|nvme|m\.2\s*sata\s*ssd|sata\s*ssd|hard\s*drive|hdd|ssd)\b|\b(m\.2\s*nvme(?:\s*ssd)?|nvme\s*ssd|nvme|m\.2\s*sata\s*ssd|sata\s*ssd|hard\s*drive|hdd|ssd)\b[^\n,;+|]{0,45}?\b(\d+(?:\.\d+)?)\s*(tb|gb)\b/ig; let m;
 while((m=rx.exec(raw))){const size=`${m[1]||m[5]}${String(m[2]||m[6]).toUpperCase()}`;const kind=(m[3]||m[4]||"").toLowerCase();const type=/nvme/.test(kind)?"NVME M.2":/hdd|hard/.test(kind)?"HDD":"SSD"; if(!found.some(d=>d.size===size&&d.type===type))found.push({size,type});}
 return found.slice(0,8);
}
function simpleListing(text){
 const t=String(text||""); const cpu=(typeof detectCPUFromListing==="function"&&detectCPUFromListing(t))||((t.match(/(?:ryzen\s+[3579]\s+\d{4,5}[a-z0-9]*|i[3579][ -]?\d{4,5}[a-z]{0,2})/i)||[])[0]||""); const gpu=(typeof detectGPUFromListing==="function"&&detectGPUFromListing(t))||((t.match(/(?:rtx|gtx)\s*\d{3,4}(?:\s*ti|\s*super)?|rx\s*\d{4}\s*(?:xtx|xt)?/i)||[])[0]||""); const priceMatches=[...t.matchAll(/(?:asking|ask|price|listed(?:\s+at)?|want(?:ing)?)\s*[:\-]?\s*\$?\s*([\d,]+)/ig)]; let price=priceMatches.length?num(priceMatches.at(-1)[1].replace(/,/g,"")):0; if(!price){const all=[...t.matchAll(/\$\s*([\d,]{2,})/g)];price=all.length?num(all.at(-1)[1].replace(/,/g,"")):0}
 const ramMatch=t.match(/\b(\d)\s*x\s*(\d+)\s*gb\b/i); const ramDirect=t.match(/\b(8|16|24|32|48|64|96|128)\s*gb\s*(?:ram|ddr[345])?/i); const ram=ramMatch?`${num(ramMatch[1])*num(ramMatch[2])}GB`:(ramDirect?`${ramDirect[1]}GB`:""); const ramType=(t.match(/\bddr\s*([345])\b/i)||[])[1];
 const motherboard=((t.split(/\n|•|\|/).find(l=>/motherboard|mobo|\b(?:a|b|x|z|h)\d{3}\b/i.test(l)))||"").trim(); const psu=((t.split(/\n|•|\|/).find(l=>/psu|power supply|\d{3,4}\s*w/i.test(l)))||"").trim();
 return {listing:t,cpu,gpu,ram,ramType:ramType?`DDR${ramType}`:"",motherboard,psu,price,currency:/\bUSD\b|US\$/i.test(t)?"USD":"CAD",drives:detectDrives(t)};
}
function snapshotCurrentBuild(){
 if(!$('cpu'))return getState();
 const s={listing:currentListing(),cpu:val('cpu'),gpu:val('gpu'),ram:val('ram'),ramType:val('ramType'),storageType:val('storageType'),storageSize:val('storageSize'),motherboard:val('motherboard'),psu:val('psu'),cooler:val('cooler'),caseQuality:val('caseQuality'),condition:val('condition'),price:num(val('price')),currency:val('currency')||'CAD'};
 s.drives=detectDrives(s.listing); const c=safeFindCPU(s.cpu),g=safeFindGPU(s.gpu); s.cpuPerformance=perfOf(c);s.gpuPerformance=perfOf(g);s.cpuValue=valueOf(c);s.gpuValue=valueOf(g);
 try{s.estimate=typeof getCurrentEstimatedSystemValue==='function'?num(getCurrentEstimatedSystemValue()):estimateSystem(s)}catch{s.estimate=estimateSystem(s)}
 s.savedAt=Date.now(); return saveState(s);
}
function ramValue(s){const gb=parseInt(s.ram)||0;const per=s.ramType==='DDR5'?2.0:s.ramType==='DDR4'?1.45:0.8;return Math.round(gb*per)}
function storageValue(s){let total=0;const drives=s.drives?.length?s.drives:(s.storageSize?[{size:s.storageSize,type:s.storageType}]:[]);drives.forEach(d=>{const m=d.size.match(/[\d.]+/);let cap=num(m?.[0]);if(/TB/i.test(d.size))cap*=1000;const rate=d.type==='NVME M.2'?0.07:d.type==='SSD'?0.05:0.02;total+=cap*rate});return Math.round(total)}
function coolerValue(s){return ({'Stock cooler':10,'Low-profile air cooler':35,'Single-tower air cooler':40,'Dual-tower air cooler':65,'Premium air cooler':95,'120mm AIO':35,'240mm AIO':60,'280mm AIO':75,'360mm AIO':90,'420mm AIO':110,'Custom loop':150,'Air cooler':40}[s.cooler]||0)}
function boardValue(s){if(!s.motherboard)return 0;if(/x870|x670e|z890|z790|x570/i.test(s.motherboard))return 170;if(/b850|b650|b550|b760|b660/i.test(s.motherboard))return 120;return 75}
function psuValue(s){if(!s.psu)return 0;const w=extractPSUW(s.psu);let v=w>=1000?115:w>=850?90:w>=750?75:w>=650?60:45;if(/gold|platinum|titanium|rmx|seasonic|focus|prime|supernova/i.test(s.psu))v+=20;return v}
function caseValue(s){return ({premium:120,mid:70,basic:35}[s.caseQuality]||0)}
function estimateSystem(s){const c=safeFindCPU(s.cpu),g=safeFindGPU(s.gpu);const base=valueOf(c)||num(s.cpuValue);const gv=valueOf(g)||num(s.gpuValue);const mult=s.condition==='excellent'?1.05:s.condition==='fair'?0.9:s.condition==='poor'?0.7:1;return Math.round((base+gv+ramValue(s)+storageValue(s)+boardValue(s)+psuValue(s)+coolerValue(s)+caseValue(s))*mult)}
function partBreakdown(s){const cpu=valueOf(safeFindCPU(s.cpu))||num(s.cpuValue);const gpu=valueOf(safeFindGPU(s.gpu))||num(s.gpuValue);return [{name:'CPU',detected:s.cpu,value:cpu},{name:'GPU',detected:s.gpu,value:gpu},{name:'RAM',detected:[s.ram,s.ramType].filter(Boolean).join(' '),value:ramValue(s)},{name:'Storage',detected:(s.drives||[]).map(d=>`${d.size} ${d.type}`).join(' + ')||[s.storageSize,s.storageType].filter(Boolean).join(' '),value:storageValue(s)},{name:'Motherboard',detected:s.motherboard,value:boardValue(s)},{name:'PSU',detected:s.psu,value:psuValue(s)},{name:'Cooling',detected:s.cooler,value:coolerValue(s)},{name:'Case',detected:s.caseQuality,value:caseValue(s)}]}
const games={
 'Fortnite':{m:1.55,cpu:.72},'Call of Duty: Warzone':{m:.88,cpu:.86},'Cyberpunk 2077':{m:.72,cpu:.92},'Counter-Strike 2':{m:1.95,cpu:.58},'Valorant':{m:2.35,cpu:.52},'Apex Legends':{m:1.2,cpu:.78},'Grand Theft Auto V':{m:1.45,cpu:.72},'Minecraft Java':{m:1.7,cpu:.45},'Forza Horizon 5':{m:1.05,cpu:.88},'Red Dead Redemption 2':{m:.78,cpu:.92},'Rainbow Six Siege':{m:1.85,cpu:.68},'Overwatch 2':{m:1.7,cpu:.65}
};
function perf(s){const c=safeFindCPU(s.cpu),g=safeFindGPU(s.gpu);return {cpu:perfOf(c)||num(s.cpuPerformance),gpu:perfOf(g)||num(s.gpuPerformance)}}
function modelFPS(s,game='Fortnite',res='1080',preset='high'){const p=perf(s);if(!p.cpu||!p.gpu)return null;const gm=games[game]||games.Fortnite;const cpuGate=clamp(p.cpu/Math.max(p.gpu*gm.cpu,1),.55,1.12);const resM={1080:1,1440:.72,2160:.43}[res]||1;const presetM={low:1.35,medium:1.16,high:1,ultra:.82}[preset]||1;const avg=Math.round(Math.max(18,p.gpu*2.05*gm.m*cpuGate*resM*presetM));return {avg,low:Math.round(avg*.72),min:Math.round(avg*.86),max:Math.round(avg*1.14)}}
function bottleneck(s,res='1080'){const p=perf(s);if(!p.cpu||!p.gpu)return {label:'Unknown',text:'CPU and GPU are required.'};const resFactor=res==='1080'?1:res==='1440'?.86:.72;const ratio=(p.cpu/resFactor)/p.gpu;if(ratio<.62)return {label:'CPU-limited',text:'The CPU is relatively weak for this GPU, especially at lower resolutions.'};if(ratio>1.7)return {label:'GPU-limited',text:'The GPU is the main performance limit. A future GPU upgrade would make the biggest gaming difference.'};return {label:'Well balanced',text:'CPU and GPU are in a reasonable performance range for each other.'}}
function powerEstimate(s){const p=perf(s);const gpuW=clamp(Math.round(80+p.gpu*3.25),75,500);const cpuW=clamp(Math.round(35+p.cpu*1.2),45,230);return Math.round(gpuW+cpuW+90)}
function psuHeadroom(s){const watt=extractPSUW(s.psu);const draw=powerEstimate(s);if(!watt)return {label:'Unknown',text:`Estimated gaming/load draw is roughly ${draw}W, but PSU wattage was not detected.`};const head=watt-draw;return {label:head>=180?'Good':head>=90?'Okay':'Low',text:`Approx. ${draw}W system draw vs ${watt}W PSU (${head}W estimated headroom).`,head}}
function targetRes(s){const p=perf(s);if(!p.gpu)return {label:'Unknown',text:'GPU required.'};if(p.gpu>=75)return {label:'4K / 1440p',text:'Best suited to high-refresh 1440p or 4K depending on the game.'};if(p.gpu>=48)return {label:'1440p',text:'A strong fit for 1440p gaming; 1080p high-refresh is also viable.'};return {label:'1080p',text:'Best matched to 1080p for a more consistent experience.'}}
function redFlags(text){const rules=[[/untested|can't test|cannot test|as[- ]is/i,'Untested / sold as-is'],[/need gone|must sell today|urgent sale/i,'Pressure / urgent-sale wording'],[/no returns|final sale/i,'No-return wording'],[/don't know specs|not sure specs|idk specs/i,'Seller does not know the specifications'],[/crash|bsod|artifact|overheat|shut(?:s)? off/i,'Stability or thermal issue mentioned'],[/mining|mined on|crypto/i,'Possible mining use'],[/deposit|e-transfer.*first|etransfer.*first|shipping only/i,'Payment/shipping risk wording'],[/password locked|icloud locked|bios locked/i,'Device lock mentioned']];return rules.filter(r=>r[0].test(text)).map(r=>r[1])}
function listingQuality(s){const fields=['cpu','gpu','ram','ramType','motherboard','psu','cooler','caseQuality','price'];let got=fields.filter(k=>s[k]).length;got+=s.drives?.length?1:0;let q=Math.round(got/10*80);if(/works|tested|benchmark|temperature|temp/i.test(s.listing||''))q+=8;if(/receipt|box|warranty/i.test(s.listing||''))q+=5;if(/model|spec/i.test(s.listing||''))q+=4;return clamp(q,0,100)}
function sellerConfidence(s){return clamp(100-redFlags(s.listing||'').length*13-(100-listingQuality(s))*.28,20,100)}
function riskScore(s){let score=redFlags(s.listing||'').length*12;if(s.price&&estimateSystem(s)&&s.price<estimateSystem(s)*.48)score+=25;if(!s.psu)score+=5;if(!s.motherboard)score+=4;if(listingQuality(s)<40)score+=12;return clamp(Math.round(score),0,100)}
function upgradePath(s){let x=45;const text=`${s.cpu} ${s.motherboard} ${s.ramType}`;if(/AM5|B650|B850|X670|X870/i.test(text))x=92;else if(/LGA\s*1851|Z890|B860/i.test(text))x=84;else if(/LGA\s*1700|B760|Z790/i.test(text))x=62;else if(/AM4|B550|X570/i.test(text))x=58;else if(/DDR3|LGA115|AM3/i.test(text))x=25;if(extractPSUW(s.psu)>=850)x+=4;if(s.ramType==='DDR5')x+=3;return clamp(x,0,100)}
function componentAge(name){const t=String(name||'').toLowerCase();let year=null;if(/rtx\s*50\d0|rx\s*9\d{3}/i.test(t))year=2025;else if(/rtx\s*40\d0|rx\s*7\d{3}/i.test(t))year=2022;else if(/rtx\s*30\d0|rx\s*6\d{3}/i.test(t))year=2020;else if(/rtx\s*20\d0|gtx\s*16\d0/i.test(t))year=2018;else if(/ryzen\s*\d\s*9\d{3}|i[3579]-?1[45]\d{3}/i.test(t))year=2024;else if(/ryzen\s*\d\s*7\d{3}|i[3579]-?1[23]\d{3}/i.test(t))year=2022;else if(/ryzen\s*\d\s*5\d{3}|i[3579]-?1[01]\d{3}/i.test(t))year=2020;else if(/ryzen\s*\d\s*[1234]\d{3}|i[3579]-?[6-9]\d{3}/i.test(t))year=2017;return year}
function upgradeRec(s){const p=perf(s);if(!p.cpu||!p.gpu)return {name:'Need more specs',reason:'Detect both CPU and GPU to produce an upgrade recommendation.'};if(parseInt(s.ram)<16)return {name:'RAM',reason:'Less than 16GB can hurt modern gaming and multitasking.'};if(!s.storageType||s.storageType==='HDD')return {name:'NVMe SSD',reason:'Fast solid-state storage improves responsiveness and game loading.'};if(p.cpu<p.gpu*.62)return {name:'CPU / platform',reason:'The CPU is the clearest performance imbalance in this build.'};if(p.gpu<p.cpu*.65)return {name:'GPU',reason:'The GPU is the clearest gaming-performance limit.'};if(psuHeadroom(s).label==='Low')return {name:'PSU',reason:'Power headroom is tight for this hardware.'};return {name:'No urgent upgrade',reason:'The detected parts are reasonably balanced. Upgrade based on your specific games or workload.'}}
function compatibility(s){const rows=[];if(!s.cpu)rows.push({ok:null,text:'CPU not detected'});if(!s.motherboard)rows.push({ok:null,text:'Motherboard not provided — socket/chipset cannot be fully verified.'});if(s.cpu&&s.motherboard&&typeof checkCPUAndMotherboard==='function'){try{const r=checkCPUAndMotherboard(s.cpu,s.motherboard);rows.push({ok:r?.compatible!==false,text:r?.message||r?.reason||(r?.compatible===false?'Possible CPU/motherboard mismatch':'CPU/motherboard platform appears compatible')})}catch{rows.push({ok:null,text:'Platform database could not verify this exact motherboard.'})}}else if(s.cpu&&s.motherboard)rows.push({ok:null,text:'CPU and motherboard detected; exact platform verification unavailable on this page.'});if(s.ramType&&/AM5|B650|B850|X670|X870/i.test(`${s.cpu} ${s.motherboard}`))rows.push({ok:s.ramType==='DDR5',text:`AM5-class platform with ${s.ramType}`});if(s.ramType&&/AM4|B450|B550|X470|X570/i.test(`${s.cpu} ${s.motherboard}`))rows.push({ok:s.ramType==='DDR4',text:`AM4-class platform with ${s.ramType}`});const ph=psuHeadroom(s);rows.push({ok:ph.label==='Good'?true:ph.label==='Low'?false:null,text:`PSU headroom: ${ph.text}`});return rows}
function negotiations(s){const est=estimateSystem(s),ask=num(s.price);if(!est&&!ask)return {};const anchor=Math.min(ask||est,est||ask);return {start:Math.round(anchor*.86/5)*5,target:Math.round(anchor*.93/5)*5,max:Math.round(Math.min(ask||Infinity,est*1.02)/5)*5}}
function resale(s){const est=estimateSystem(s);const quality=listingQuality(s);const list=Math.round(est*(1.06+(quality>=75?.04:0))/10)*10;return {low:Math.round(est*.95/10)*10,target:list,high:Math.round(est*1.14/10)*10}}
function overall(s){const est=estimateSystem(s),ask=num(s.price);const value=est&&ask?clamp(Math.round(70+(est-ask)/est*90),10,100):55;const p=perf(s);const gaming=clamp(Math.round((p.cpu*.35+p.gpu*.65)||45),10,100);const quality=clamp(Math.round((s.psu?72:48)+(s.cooler?8:0)+(s.caseQuality==='premium'?12:s.caseQuality==='mid'?6:0)),20,100);const upgrade=upgradePath(s);const seller=Math.round(sellerConfidence(s));const risk=riskScore(s);const total=Math.round(value*.28+gaming*.25+quality*.14+upgrade*.14+seller*.19-risk*.08);return {value,gaming,quality,upgrade,seller,risk,total:clamp(total,0,100)}}
function testingChecklist(s){const items=[['Power-on','Cold boot the PC and confirm it reaches Windows normally.'],['CPU','Run a CPU load test and watch temperatures, clocks and crashes.'],['GPU','Run a graphics load/game and watch for crashes, visual artifacts and abnormal temperatures.'],['Memory','Confirm the advertised RAM capacity and that the system remains stable under load.']];if((s.drives||[]).length||s.storageSize)items.push(['Storage','Check SMART/CrystalDiskInfo health and verify each advertised drive appears.']);if(s.psu)items.push(['PSU','Confirm the exact PSU model/wattage physically matches the listing.']);else items.push(['PSU','Ask to see the PSU label before buying; the listing did not identify it.']);if(s.cooler?.includes('AIO'))items.push(['AIO cooler','Listen for unusual pump noise and watch CPU temperatures during a sustained load.']);items.push(['Physical inspection','Check ports, fans, dust, screws, damage and signs of rushed repairs.']);return items}
function sellerQuestions(s){const q=[];if(!s.psu)q.push('What is the exact PSU brand, model and wattage?');if(!s.motherboard)q.push('What is the exact motherboard model?');if(!(s.drives||[]).length)q.push('What storage drives are installed, and can you send a CrystalDiskInfo health screenshot?');else q.push('Can you send a CrystalDiskInfo health screenshot for the storage drive(s)?');if(!s.cooler)q.push('What CPU cooler is installed?');q.push('Has the GPU or PC ever been repaired or had stability issues?','Can I see the PC running a game or stress test before buying?','What CPU and GPU temperatures does it reach under load?','Are there any passwords, account locks, BIOS locks or missing accessories?');return q.slice(0,8)}
function setText(id,text,cls){const e=$(id);if(e){e.textContent=text;if(cls)e.className=cls}}
function initDashboard(){const s=getState(),o=overall(s),q=listingQuality(s);setText('overallScore',s.cpu||s.gpu?o.total:'—');$('overallRing')?.style.setProperty('--score',s.cpu||s.gpu?o.total:0);setText('overallVerdict',o.total>=90?'Excellent overall':o.total>=80?'Very strong':o.total>=70?'Good overall':o.total>=55?'Mixed / fair':'Needs caution');setText('dashboardBuild',[s.cpu,s.gpu].filter(Boolean).join(' + ')||'No saved build yet');[['valueScore',o.value],['gamingScore',o.gaming],['qualityScore',o.quality],['upgradeScore',o.upgrade],['sellerScore',o.seller]].forEach(([i,v])=>setText(i,`${v}/100`));setText('riskLabel',o.risk<25?'LOW':o.risk<50?'MEDIUM':'HIGH',o.risk<25?'big good':o.risk<50?'big warn':'big bad');setText('listingQuality',`${q}/100`);if($('listingQualityBar'))$('listingQualityBar').style.width=`${q}%`;setText('listingQualityText',q>=80?'Detailed listing with strong decision-useful information.':q>=55?'Decent listing, but some important details are still missing.':'Sparse listing — verify specifications before judging the deal.');const est=estimateSystem(s),r=resale(s),u=upgradeRec(s);if($('summaryKpis'))$('summaryKpis').innerHTML=[['Asking',money(s.price)],['Estimated value',money(est)],['Best for',targetRes(s).label],['Upgrade first',u.name],['Potential resale',money(r.target)]].map(x=>`<div class="kpi"><span class="muted">${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}
function initPerformance(){const s=getState();const sel=$('gameSelect');if(sel)sel.innerHTML=Object.keys(games).map(g=>`<option>${g}</option>`).join('');const render=()=>{const g=val('gameSelect'),r=val('resolutionSelect'),pr=val('presetSelect'),f=modelFPS(s,g,r,pr);if(!f){setText('gameFps','—');setText('fpsRange','Analyze a CPU and GPU first.');return}setText('gameFps',`~${f.avg} FPS`);setText('oneLow',`~${f.low} FPS`);setText('fpsRange',`Modelled range: ~${f.min}–${f.max} FPS`);const exp=f.avg>=165?'High refresh':f.avg>=100?'Very smooth':f.avg>=60?'Smooth':'Demanding';setText('experienceLabel',exp);setText('experienceText',`${g} at ${r==='2160'?'4K':r+'p'} ${pr} settings.`);const b=bottleneck(s,r);setText('bottleneckLabel',b.label);setText('bottleneckText',b.text);const ph=psuHeadroom(s);setText('psuHeadroom',ph.label);setText('psuText',ph.text);const tr=targetRes(s);setText('targetResolution',tr.label);setText('targetResolutionText',tr.text);setText('valuePerFps',s.price?`${money(s.price/f.avg)} / FPS`:'—')};$('estimateGameBtn')?.addEventListener('click',render);['gameSelect','resolutionSelect','presetSelect'].forEach(i=>$(i)?.addEventListener('change',render));render()}
function initHardware(){const s=getState();const c=compatibility(s);if($('compatibilityList'))$('compatibilityList').innerHTML=c.map(x=>`<div class="kpi"><span>${x.ok===true?'✅':x.ok===false?'⚠️':'❔'} ${x.text}</span></div>`).join('');const up=upgradePath(s);setText('upgradePathScore',`${up}/100`);if($('upgradePathBar'))$('upgradePathBar').style.width=`${up}%`;setText('upgradePathText',up>=80?'Modern platform with strong future options.':up>=55?'Reasonable upgrade path, though the platform has some limits.':'Older or constrained platform; major upgrades may require multiple parts.');const parts=partBreakdown(s),total=parts.reduce((a,b)=>a+b.value,0);if($('valueBreakdownBody'))$('valueBreakdownBody').innerHTML=parts.map(p=>`<tr><td>${p.name}</td><td>${p.detected||'<span class="muted">Unknown</span>'}</td><td>${money(p.value)}</td><td>${total?Math.round(p.value/total*100):0}%</td></tr>`).join('');setText('breakdownTotal',money(total));const u=upgradeRec(s);setText('upgradeRecommendation',u.name);setText('upgradeReason',u.reason);const now=new Date().getFullYear();if($('ageList'))$('ageList').innerHTML=[['CPU',s.cpu],['GPU',s.gpu]].map(([label,name])=>{const y=componentAge(name);return `<div class="kpi"><span>${label}: ${name||'Unknown'}</span><strong>${y?`~${now-y} yrs old`:'Age unknown'}</strong></div>`}).join('');const drives=s.drives?.length?s.drives:detectDrives(s.listing||'');if($('driveList'))$('driveList').innerHTML=drives.length?drives.map((d,i)=>`<div class="card"><h3>Drive ${i+1}</h3><div class="big">${d.size}</div><div class="tiny">${d.type}</div></div>`).join(''):'<div class="notice">No individual drives could be identified from the saved listing.</div>'}
function initBuying(){const s=getState(),n=negotiations(s),r=riskScore(s);setText('startOffer',n.start?money(n.start):'—');setText('targetOffer',n.target?money(n.target):'—');setText('maxOffer',n.max?money(n.max):'—');setText('riskScore',r);$('riskRing')?.style.setProperty('--score',r);setText('riskWord',r<25?'Low':r<50?'Medium':'High',r<25?'big good':r<50?'big warn':'big bad');setText('riskExplanation',r<25?'No major text-based warning pattern was detected. Still inspect the PC in person.':r<50?'Some missing information or warning language deserves verification.':'Multiple risk signals were detected; verify the listing carefully before considering the purchase.');const qs=sellerQuestions(s);if($('sellerQuestions'))$('sellerQuestions').innerHTML=qs.map(q=>`<li>${q}</li>`).join('');$('copyQuestions')?.addEventListener('click',()=>navigator.clipboard?.writeText(qs.map(q=>`• ${q}`).join('\n')));if($('testingChecklist'))$('testingChecklist').innerHTML=testingChecklist(s).map(([h,t])=>`<div class="card"><h3>✓ ${h}</h3><div class="tiny">${t}</div></div>`).join('')}
function compareScore(s){const e=estimateSystem(s),p=perf(s),fps=modelFPS(s,'Fortnite','1440','high')?.avg||0;return {est:e,perf:Math.round(p.cpu*.35+p.gpu*.65),fps,value:e&&s.price?Math.round(e/s.price*100):0}}
function initCompare(){$('compareBtn')?.addEventListener('click',()=>{const a=simpleListing(val('compareA')),b=simpleListing(val('compareB'));const ca=compareScore(a),cb=compareScore(b);const rows=[['CPU',a.cpu||'Unknown',b.cpu||'Unknown','—'],['GPU',a.gpu||'Unknown',b.gpu||'Unknown','—'],['RAM',a.ram||'Unknown',b.ram||'Unknown','—'],['Asking Price',moneyFor(a.price,a.currency),moneyFor(b.price,b.currency),a.price&&b.price?(a.price<b.price?'A':'B'):'—'],['Estimated Value',moneyFor(ca.est,a.currency),moneyFor(cb.est,b.currency),ca.est>cb.est?'A':cb.est>ca.est?'B':'Tie'],['1440p Fortnite',ca.fps?`~${ca.fps} FPS`:'—',cb.fps?`~${cb.fps} FPS`:'—',ca.fps>cb.fps?'A':cb.fps>ca.fps?'B':'Tie'],['Value Index',ca.value||'—',cb.value||'—',ca.value>cb.value?'A':cb.value>ca.value?'B':'Tie']];if($('compareTableBody'))$('compareTableBody').innerHTML=rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('');const pointsA=(ca.value>cb.value)+(ca.fps>cb.fps)+(ca.est>cb.est),pointsB=(cb.value>ca.value)+(cb.fps>ca.fps)+(cb.est>ca.est);setText('compareWinner',pointsA>pointsB?'PC A wins overall':pointsB>pointsA?'PC B wins overall':'Very close / tie');if($('compareResults'))$('compareResults').style.display='block'})}
function moneyFor(v,c='CAD'){return v?new Intl.NumberFormat('en-CA',{style:'currency',currency:c||'CAD',maximumFractionDigits:0}).format(v):'—'}
function initFlip(){const s=getState(),r=resale(s);if($('purchasePrice'))$('purchasePrice').value=s.price||'';const calc=()=>{const buy=num(val('purchasePrice')),extra=num(val('extraCosts')),fees=num(val('sellingFees'))/100,res=r.target,sellCost=res*fees,profit=res-buy-extra-sellCost,margin=res?profit/res*100:0;setText('resaleEstimate',money(res));setText('resaleRange',`${money(r.low)} – ${money(r.high)} likely listing range`);setText('profitEstimate',money(profit),profit>=0?'big good':'big bad');setText('profitMargin',`${margin.toFixed(1)}%`,margin>=15?'big good':margin>=5?'big warn':'big bad');const rating=margin>=20?'Strong flip':margin>=10?'Possible flip':margin>0?'Thin margin':'Not a flip';setText('flipRating',rating);setText('flipText',margin>=10?'There appears to be room for resale costs and negotiation.':'The margin may disappear after time, parts, transport or unexpected repairs.')};$('calculateFlip')?.addEventListener('click',calc);calc()}
function hookAnalyzer(){if(!$('listingText'))return;const save=()=>setTimeout(snapshotCurrentBuild,50);const oldParse=window.parseListing;if(typeof oldParse==='function'&&!oldParse.__v4){window.parseListing=function(){const r=oldParse.apply(this,arguments);save();return r};window.parseListing.__v4=true}const oldAnalyze=window.analyzeDeal;if(typeof oldAnalyze==='function'&&!oldAnalyze.__v4){window.analyzeDeal=function(){const r=oldAnalyze.apply(this,arguments);save();return r};window.analyzeDeal.__v4=true}['cpu','gpu','ram','ramType','storageType','storageSize','motherboard','psu','cooler','caseQuality','condition','price','currency','listingText'].forEach(i=>$(i)?.addEventListener('change',snapshotCurrentBuild));}
window.PCDEAL_V4={getState,saveState,snapshotCurrentBuild,detectDrives,simpleListing,modelFPS,bottleneck,psuHeadroom,targetRes,listingQuality,riskScore,upgradePath,partBreakdown,compatibility,negotiations,resale,overall};
document.addEventListener('DOMContentLoaded',()=>{hookAnalyzer();const p=document.body.dataset.page;if(p==='dashboard')initDashboard();if(p==='performance')initPerformance();if(p==='hardware')initHardware();if(p==='buying')initBuying();if(p==='compare')initCompare();if(p==='flip')initFlip()});
})();
